name: coding_programming_tabview
description: TabView/NavigationBar for our FBLA Coding & Programming app submission.
version: 1.0.1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_bar_with_sheet: ^2.4.0
  mad2_browsepage: ^1.3.7
  mad2_home: ^1.1.2
  mad2_shop: ^1.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
